x=int(input("enter digit: "))
if(x==1):
    print("one")
if(x==2):
    print("two")
if(x==3):
    print("three")
if(x==4):
    print("four")
if(x==5):
    print("five")
if(x==6):
    print("six")
if(x==7):
    print("seven")
if(x==8):
    print("eight")
elif(x==9):
    print("nine")
elif(x==10):
    print("ten")
